# NumPy Tutorial

Its a multidimensional array library. 1D, 2D, 3D arrays.

Why Numpy is faster then list?
- Numpy use less bytes of memory cus it has fixed type.
- No type checking when iterating through objects
- Use contiguous memory(all block are right next to each other, only need to store start of memory, size and type)
    - SIMD Vector Processing
    - Effective Cache Utilization

In [ ]:
#List
a = [1, 2, 3]

#NumPy
a = np.array([1, 2, 3])

#### Load in NumPy

In [1]:
import numpy as np

#### The Basics

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1, 2, 3], ['a', 'b', 'c']])
print(b)

[['1' '2' '3']
 ['a' 'b' 'c']]


In [7]:
# Get Dimension
print('a dimension: ', a.ndim)
print('b dimension: ', b.ndim)

a dimension:  1
b dimension:  2


In [8]:
# Get Shape
b.shape

(2, 3)

In [9]:
# Get Type
a.dtype

dtype('int64')

In [11]:
# to store a in specified type
a = np.array([1, 2, 3], dtype= 'int16')
print('New \'a\' data type : ', a.dtype)

New 'a' data type :  int16


In [17]:
# Get size
a.itemsize

2

In [15]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)

6
6


#### Accessing/ Changing specific elements, rows, columns, etc

In [18]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
a.shape

(2, 7)

In [24]:
# Get a specific elements [r, c] to get 13 : r= 1, c = 5
print(a[1,5])

# similerly we can do a[1, -2]
a[1, -2]

13


13

In [26]:
# Get a specific row 
a[0, :] # : for all

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get specific column
a[:, 2]

array([ 3, 10])

In [29]:
# Getting little more fancy [startindex: endindex: stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [30]:
a[1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [32]:
a[:, 2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [34]:
a[:, 2] = [3, 10]
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [36]:
# 3d example

b = np.array([[[1, 2],[3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [37]:
# Get specific element (work outside in): to get 4

b[0,1,1]


4

In [40]:
# replace (need to be same dimension)
b[:,1,:] = [[9, 9],[8, 8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#### Initilizing Different Types of Array

In [43]:
# All 0s matrix

np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
# All 1s matrix

np.ones((4, 2, 2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [45]:
# All other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [48]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [49]:
# Random decimal numbers (between 0 and 1)
np.random.rand(4,2)

array([[0.86863283, 0.02166329],
       [0.77462456, 0.98374929],
       [0.80282317, 0.70479364],
       [0.68160298, 0.65504615]])

In [50]:
# Random sample
np.random.random_sample(a.shape)

array([[0.73690754, 0.0164355 , 0.96918394, 0.958146  , 0.4254974 ,
        0.13498288, 0.53000766],
       [0.13563222, 0.52338031, 0.43261527, 0.90544726, 0.56456394,
        0.06961867, 0.81876117]])

In [55]:
# Random Integer values
np.random.randint(7)

2

In [56]:
np.random.randint(4,7, size= (3, 3)) # 7 is exclusive

array([[4, 4, 6],
       [6, 4, 5],
       [6, 5, 5]])

In [57]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [65]:
output = np.ones((5, 5))

z = np.zeros((3, 3))
z[1,1] = 9

output[1:4, 1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

>Be careful when copying arrays!!!

In [66]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a) # 'a' automatically changes with 'b' cus var name 'b' point as same as 'a' does

array([100,   2,   3])

In [70]:
# We can use .copy() 
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a) # a remains same
print(b)

[1 2 3]
[100   2   3]


#### Mathematics

In [71]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [72]:
a+2 #cann do all sorts of operation i:e + - * /

array([3, 4, 5, 6])

In [73]:
b = np.array([1,0,1,0])
a + b 

array([2, 2, 4, 4])

In [74]:
a**2

array([ 1,  4,  9, 16])

In [75]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [77]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [79]:
# cant do a * b
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [80]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [81]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
# min and max
np.min(stats)

1

In [82]:
np.min(stats, axis=0)

array([1, 2, 3])

In [83]:
np.max(stats, axis = 1)

array([3, 6])

In [88]:
np.sum(stats)

21

In [87]:
np.sum(stats, axis = 0)

array([5, 7, 9])

#### Reorganizing Arrays

In [91]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8, 1))
after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [93]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [94]:
np.hstack([v1, v2, v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

In [95]:
# Horixontal stack

h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous
##### Load Data from File

In [99]:
filedata = np.genfromtxt('data.txt', delimiter= ',')
print(filedata)

filedata.astype('int32')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


##### Boolean Masking and Advancing Indexing

In [100]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [101]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [102]:
# you can index with a list in NumPy

a = np.array([1,2,3,4,5,6])
a[3]

4

In [104]:
a[[1,3,4]]

array([2, 4, 5])

In [107]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [108]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [109]:
np.any(filedata > 50, axis = 1) # axis = 1 for rows

array([ True,  True,  True])

In [111]:
[(filedata > 50) & (filedata < 100)]

[array([[False, False, False, False, False,  True, False, False, False,
         False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False,  True, False,  True, False,
         False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False,  True,
         False, False, False, False, False, False, False,  True,  True]])]

In [110]:
filedata[(filedata > 50) & (filedata < 100)]

array([75., 75., 55., 78., 76., 88.])

In [ ]:
a[2:4,0:2]
a[]